import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.scss";
import { SITE_NAME } from "@/constants/seo.constants";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/app/[lang]/providers";
import { dir } from "i18next";
import { languages } from "@/app/i18n/settings";

const zen = Noto_Sans({
	subsets: ["cyrillic", "latin"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
	variable: "--font-zen",
	style: ["normal"],
});

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`,
	},
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }));
}

export default function RootLayout({
	children,
	params: { lang },
}: Readonly<{
	children: React.ReactNode;
	params: { lang: string };
}>) {
	return (
		<html lang={lang} dir={dir(lang)}>
			<body className={zen.className}>
				<Providers>
					{children}
					<Toaster position="bottom-right" />
				</Providers>
			</body>
		</html>
	);
}
