import Login from "@/app/[lang]/login/Login";
import { PropsWithLocale } from "@/app/[lang]/page";
import { generateMedatada } from "@/components/Metadata/Metadata";
import { NO_INDEX_PAGE } from "@/constants/seo.constants";

import { Metadata } from "next";

type Props = {};

export const metadata: Metadata = generateMedatada({
	title: "Login",
	description: "Generated by create next app",
	...NO_INDEX_PAGE,
});

export default function LoginPage({ params: { lang } }: PropsWithLocale) {
	return <Login lang={lang} />;
};
