import Login from "@/app/login/Login";
import { generateMedatada } from "@/components/Metadata/Metadata";

import { Metadata } from "next";

type Props = {};

export const metadata: Metadata = generateMedatada({
	title: "Login",
	description: "Generated by create next app",
});

export const LoginPage = (props: Props) => {


	return <Login />;
};

export default LoginPage;
