import Login from "@/app/login/Login";
import { generateMedatada } from "@/components/Metadata/Metadata";
import { NO_INDEX_PAGE } from "@/constants/seo.constants";

import { Metadata } from "next";

type Props = {};

export const metadata: Metadata = generateMedatada({
	title: "Login",
	description: "Generated by create next app",
	...NO_INDEX_PAGE,
});

export const LoginPage = () => {
	return <Login />;
};

export default LoginPage;
