import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "@/app/providers";
import { generateMedatada } from "@/components/Metadata/Metadata";

export const metadata: Metadata = generateMedatada({
	title: "Create Next App",
	description: "Generated by create next app",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
